AWSTemplateFormatVersion: 2010-09-09
Description: HelloWorld Lambda function template for Application Load Balancer Lambda
  as target
Outputs:
  HelloWorldFunctionARN:
    Description: ARN of the HelloWorld Lambda function
    Value:
      Fn::GetAtt:
      - HelloWorldFunction
      - Arn
Resources:
  HelloWorldFunction:
    Properties:
      CodeUri: s3://aws-support-elb/helloworld/0ed0511ba36fc78be8db720769185ba2
      Description: An Lambda function that returns "HelloWorld"
      Handler: helloworld_27.lambda_handler
      Runtime: python2.7
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
